---
- hosts: all
  become: true
  tasks: 
  - name: Install apache httpd
    apt:
     name: apache2
     state: latest
  - name: start the httpd module
    service: 
     name: apache2
     state: started
     enabled: true
...
