---
- hosts: all
  become: true
  tasks: 
  - name: Get Git Version
    shell: git --version
    register: gitVersion
    ignore_errors: yes
  - name: Display the msg wheather git is installed or not 
    when: gitVersion.stdout == ""
    debug: 
      msg: "Git is not installed"
  - name: Installing the Git
    when: gitVersion.stdout == ""
    apt: 
      name: git
      state: present
  - name: Get Git Version
    shell: git --version
    register: gitVersion
  - name: Display the Git Version
    when: gitVersion.stdout != ""
    debug: 
      msg: "Git is installed and versionis {{gitVersion.stdout}}"
...
