---
- hosts: all
  become: true
  tasks: 
  - name: Install list of packages
    apt: name="{{item}}" state=present
    with_items: 
    - git
    - unzip
    - tar
    - curl
    - wget
    - apache2
    - nano
...
